[bluetooth]
    adapter = "hci0"

[socket]
    path = "/tmp/itd/socket"

[metrics]
    enabled = false

    [metrics.heartRate]
        enabled = true

    [metrics.stepCount]
        enabled = true

    [metrics.battLevel]
        enabled = false

    [metrics.motion]
        # This may lower the battery life of the PineTime
        enabled = false

[conn]
    reconnect = true

[conn.whitelist]
    enabled = false
    devices = []

[on.connect]
    notify = false

[on.reconnect]
    notify = false
    setTime = true

[notifs.translit]
    use = ["eASCII", "Emoji"]

[notifs.ignore]
    sender = []
    summary = ["InfiniTime"]
    body = []

[music]
    vol.interval = 5

[weather]
    enabled = true
    location = "Rome, GA"

[logging]
    level = "info"
